import type { Metadata } from "next";
import { Schibsted_Grotesk, Martian_Mono } from "next/font/google";
import "./globals.css";
import LightRays from "./component/lightrays";
import Navbar from "./component/Navbar";

const MartianMono = Martian_Mono({
  variable: "--font-Martian-Mono",
  subsets: ["latin"],
});

const SchibstedGrotesk = Schibsted_Grotesk({
  variable: "--font-Schibsted-Grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevEvent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SchibstedGrotesk.variable} ${MartianMono.variable} min-h-screen antialiased`}
      >

      <Navbar/>

        <div className="absolute inset-0 top-0 z-[-1] min-h-screen">
          <LightRays
    // raysOrigin="top-center-offset"
    // raysColor="#5dfeca"
    // raysSpeed={0.5}
    // lightSpread={0.9}
    // rayLength={1.4}
    // followMouse={true}
    // mouseInfluence={0.02}
    // noiseAmount={0.0}
    // distortion={0.01}
    // className="custom-rays"
    raysOrigin="top-center-offset"
  raysColor="#1aff7c"
  raysSpeed={0.35}
  lightSpread={1.2}
  rayLength={1.8}
  followMouse={true}
  mouseInfluence={0.03}
  noiseAmount={0.03}
  distortion={0.02}
  className="custom-rays"
  />
        </div>

        <main>
          {children}
        </main>


  

        
      </body>
    </html>
  );
}
